In [1]:
import numpy as np

In [2]:
array = np.array([1, 4, 5, 8], float)   #cada coisa dentro de uma matriz deve ser do mesmo tipo, como int ou float.

In [3]:
array = np.array([[1, 2, 3], [4, 5, 6]], float) 

In [14]:
if True:
    array = np.array([1, 4, 5, 8], float)               #mudando para True houve os resultados da matriz apareceram no print tanto o valor inteiro, quanto o separado.
    print (array) 
    print ('')
    array = np.array([[1, 2, 3], [4, 5, 6]], float)  
    print (array)

[1. 4. 5. 8.]

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
if True:
    array = np.array([1, 4, 5, 8], float)     # Existe a opção de cortar e pegar somente algo de seu interesse no Numpy
    print (array)
    print ('')
    array[1]
    print ('')
    print (array[:2])
    print ('') 
    array[1] = 5.0
    print (array[1])

[1. 4. 5. 8.]


[1. 4.]

5.0


In [18]:
if True:
    two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
    print (two_D_array)                                                #aqui foi usado uma opção aritmetica do numpy para escolher uma das duas listas e outra para pegar um numero de cada lista.            
    print ("")
    print (two_D_array[1][1])
    print ("")
    print (two_D_array[1, :])
    print ("")
    print (two_D_array[:, 2])


[[1. 2. 3.]
 [4. 5. 6.]]

5.0

[4. 5. 6.]

[3. 6.]


In [19]:
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([5, 2, 6], float)           #aqui vemos que foi separado os elementos dentro da lista criando duas variaveis fazendo uma adição, subtração e multiplicação entre elas.
    print (array_1 + array_2)
    print ("")
    print (array_1 - array_2)
    print ("")
    print (array_1 * array_2)

[6. 4. 9.]

[-4.  0. -3.]

[ 5.  4. 18.]


In [20]:
if True:
    array_1 = np.array([[1, 2], [3, 4]], float)
    array_2 = np.array([[5, 6], [7, 8]], float)
    print (array_1 + array_2)
    print ("")
    print (array_1 - array_2)
    print ("")
    print (array_1 * array_2)


[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]

[[ 5. 12.]
 [21. 32.]]


In [23]:
array_1 = np.array([1, 2, 3], float)

In [24]:
array_2 = np.array([[6], [7], [8]], float)

In [26]:
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([[6], [7], [8]], float)
    print (np.mean(array_1))
    print (np.mean(array_2                                       #Além das operações aritmeticas padrão, a Numpy também possui bastante outras operações matemáticas que você pode aplicar aos arrays Numpy.
    print ("")
    print (np.dot(array_1, array_2

2.0
7.0

[44.]
